env:
  TERM: screen-256color
window:
  dynamic_title: true
  dimensions:
    columns: 180
    lines: 80
  position:
    x: 0
    y: 0
  padding:
    x: 0
    y: 0
  opacity: 1
  dynamic_padding: false
  decorations: full
  startup_mode: Windowed
  title: ""
scrolling:
  history: 100000
  multiplier: 1
font:
  normal:
    family: Noto Sans Mono
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  size: 10.0
colors:
  primary:
    background: '0x090300'
    foreground: '0xa5a2a2'
  cursor:
    text: '0x090300'
    cursor: '0xa5a2a2'
  normal:
    black:   '0x090300'
    red:     '0xdb2d20'
    green:   '0x01a252'
    yellow:  '0xfded02'
    blue:    '0x01a0e4'
    magenta: '0xa16a94'
    cyan:    '0xb5e4f4'
    white:   '0xa5a2a2'
  bright:
    black:   '0x5c5855'
    red:     '0xdb2d20'
    green:   '0x01a252'
    yellow:  '0xfded02'
    blue:    '0x01a0e4'
    magenta: '0xa16a94'
    cyan:    '0xb5e4f4'
    white:   '0xf7f7f7'

  indexed_colors:
#    - { index: 16, color: '0xe8bbd0' }
    - { index: 17, color: '0xcdab53' }
    - { index: 18, color: '0x3a3432' }
    - { index: 19, color: '0x4a4543' }
    - { index: 20, color: '0x807d7c' }
    - { index: 21, color: '0xd6d5d4' }
bell:
  animation: EaseOutExpo
  duration: 100
  color: '#ffffff'
selection:
  save_to_clipboard: true
cursor:
  style: Block
  unfocused_hollow: true
live_config_reload: true
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false
key_bindings:
  - { key: K,       mods: Command,         chars: "clear\n" }
