#!/bin/sh

# usage
# $1 - text-color
# $2 - bg-color
# $3 - input file (containing line separated words)
# $4 - output file (will be a png)

# get list of available fonts by
# convert -list font | grep Font
convert \
    -background $2 \
    -size 800x400 \
    -fill $1 \
    -font Source-Code-Pro-Bold \
    -pointsize 32 \
    -gravity center \
    label:"$(shuf -n 1 $3)" \
    $4

feh --bg-center $4 --bg-center $4
