[ids]
*

[main]
# ctrl-space -> enter
# alt-space -> backspace
control = layer(control_layer)
leftalt = layer(alt_layer)

[control_layer:C]
# If space is pressed while control is held, send enter
space = enter

[alt_layer:A]
# If space is pressed while alt is held, send backspace
space = backspace

[control_layer+shift]
# shift-ctrl-space -> raw ctrl-space
# This overrides the enter mapping when shift is also held
space = C-space

[alt_layer+shift]
# shift-alt-space -> raw alt-space
space = A-space
